version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    networks:
      - node_postgres_network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    command: npm run start:dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    restart: always
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    command: postgres -c logging_collector=on
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - node_postgres_network
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_PORT=${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/postgres-data
      - .:/docker-entrypoint-initdb.d

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"

volumes:
  postgres:
    name: nest-postgres-docker-db
  app:
    name: nest-docker-service

networks:
  node_postgres_network:
    driver: bridge
