version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}

  postgres:
    image: postgres:14.4-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
